name: eo_country_picker
description: A package to easily pick a country and retrieve its name, flag, ISO code, and dialing code.
version: 0.0.1
homepage: https://github.com/eijiotieno-official/eo_country_picker

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

